Fix/multiple requests listing
Nitrux/nx-software-center pull request #110
Opened 2022-02-10 13:59 UTC by milohr

The issue is that a request was being sent one after another for changes in the `page`, `pageSize`, `category`, `nameFilters`, `tags`, etc, fields.

So if a `page` and `tag` field changed closed in time, then two requests would be sent, resulting in repeated and unrelated mixed results, from both requests' replies.

My proposed solution is to use a single-shot timer to control multiple requests close in time. It has a timeout of `900 ms`, all requests within that time are ignored until the timer is timeout, then the request is sent with whatever arguments all those fields have at that moment.

2022-02-10 18:39 UTC, azubieta commented
While timers can help here there is still a chance for the same issue to happen if the network connection is too slow.

@milohr I would go for encapsulating the request and response handler into an object (class) that could be disposed if a new one is made before the later is completed.

2022-02-11 09:39 UTC, probal31 commented
@milohr Searching apps by text multiple times keeps on appending the results.

For example, Search "Instagram" shows 2 results.
Again search with text "Instagra", now again 2 apps are appended to the list (total 4).
Again searching with text "Instagram" now has total 6 apps (2 unique apps, rest are duplicates).

2022-02-11 13:41 UTC, milohr commented
> While timers can help here there is still a chance for the same issue to happen if the network connection is too slow.
> 
> @milohr I would go for encapsulating the request and response handler into an object (class) that could be disposed if a new one is made before the later is completed.

I thought about this queueing solution but it might present the following issue:

If I make a request such as:

`tags=[appimages]`
 then
 
```
 tags=[mauikit]
 nameFilter="index"
```

i will see results from the first request and then it would jump to the actual results of the second request. This is very likely to happen often due to how the StoreModel is designed: every change in any of the fields triggers a request, so to clear a "search" all the fields would end up triggering a request, meaning a big "queue"

Hope to have explained myself here.

An alternative solution, but requiering refactoring, is forcing the StoreModle API to make only request in a single package, not by every field change.

so instead of 
```
fieldChanged() -> request()
fieldChanged() -> request()
fieldChanged() -> request()
```

do
```
setField()
setField()
setField()
request()
```

2022-02-11 15:02 UTC, azubieta requested changes

2022-02-15 11:17 UTC, probal31 commented on src/models/categorymanager.h
> +class CategoryManager : public QObject {
Updated the store manager implementation. Previously category manager and application manager was separate.
Combined those implementations to the store manager

2022-02-15 11:18 UTC, probal31 commented on src/models/applicationmanager.cpp
> +        // foreach (Category *item, category->categories) {
Removed unused code

2022-02-15 11:18 UTC, probal31 commented on src/models/applicationmanager.cpp
> +ApplicationManager::ApplicationManager(QObject *parent)
Updated the implementation and added a combined logic as store manager

2022-02-15 11:18 UTC, probal31 commented on src/models/applicationmanager.cpp
> +    , m_apprepoStore(new AppRepoStore("https://apprepo.de/rest/api", this))
Added code to allow lazy loading

2022-02-16 18:21 UTC, azubieta approved these changes

2022-02-25 14:23 UTC, azubieta commented on tests/services/storemanager/teststoremanagerservice.cpp
> +void TestStoreManagerService::testGetApprepoApplications()
:+1: automatic testing is the way to great software :)

2022-04-28 08:19 UTC, UriHerrera approved these changes

2022-05-10 11:43 UTC, merged